version: '3.5'

services:
  mysql:
   image: mysql:5.7
   restart: always
   container_name: mysql_wordpress
   volumes:
    - mysql-data:/var/lib/mysql
   networks:
    - wp-net
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress

  wordpress:
   depends_on: 
     - mysql
   networks:
    - wp-net
   image: wordpress:4.7-php5.6
   restart: always
   container_name: wordpress
   volumes:
    - wp-data:/var/www/html
   ports:
    - 81:80
   environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

volumes:
    mysql-data:
    wp-data:

networks:
    wp-net:
      name: wp-net
      driver: bridge